port: 5000
host: 0.0.0.0
safe: false
permalink: /:title
# Site settings
title: "Goshrow - Blog"
email: goshrow@gmail.com
description: "Blog Posts by GOSHROW"
url: "https://goshrow.github.io/blog/"
keywords: "Blog, GOSHROW, github, goshrow, blog, tech, code"
title_description: "What I Learnt Today. "
title_image: "https://avatars2.githubusercontent.com/u/46024363?s=460&u=603841eb55caa2391882da5d4923ca35827b40bb&v=4"
# google_analytics: 
# disqus_account: 
favicon: "./favicons/favicon.ico"
touch-icon: "./favicons/apple-icon.png"
github_repository: https://github.com/jacobtomlinson/carte-noire
# addthis_id: 
post_limit: 6

# Social usernames/URLs
twitter_username: _goshrow
github_username:  GOSHROW
instagram_username: swapnil._ghosh
reddit_username: goshrow
linkedin_link: https://linkedin.com/in/goshrow
mail_id_primary: goshrow@gmail.com
mail_id_secondary: goshrow@protonmail.com
# Footer
footer_left: ""
footer_right: "BY <a href=\"https://github.com/GOSHROW/blog\"><i class=\"fa fa-github-alt\"></i></a> <a href=\"https://goshrow.github.io\"> GOSHROW </a>"

# # Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
